# DNSfookup Production Configuration Example
# Copy this to config.yaml and update with your actual values

sql:
  protocol: 'postgresql+psycopg2'
  user: 'dnsfookup_user'
  password: 'CHANGE_THIS_TO_STRONG_PASSWORD'  # Generate dengan: openssl rand -base64 32
  host: 'localhost'
  db: 'dnsfookup_prod'
  deprec_warn: false

jwt:
  secret_key: 'CHANGE_THIS_TO_VERY_STRONG_SECRET_KEY_MIN_32_CHARS'  # Generate dengan: openssl rand -base64 48
  blacklist_enabled: true
  blacklist_token_checks: ['access']
  token_expires: 21600  # 6 hours

redis:
  password: 'CHANGE_THIS_REDIS_PASSWORD'  # Generate dengan: openssl rand -base64 32
  host: '127.0.0.1'
  port: 6379
  expiration: 3600  # 1 hour - DNS record expiration
  timeout: 3

dns:
  domain: 'dns.rebind.com'  # Your DNS rebinding subdomain
  port: 53
  ip: '0.0.0.0'  # Bind to all interfaces for production
  use_failure_ip: false  # Return NXDOMAIN instead of failure IP
  failure_ip: '0.0.0.0'
  use_fail_ns: true  # Return NS record for unknown domains
  fail_ns: '8.8.8.8'  # Fallback NS server
