version: '3.8'
services:
  redis:
    image: "redis:7.4-alpine"
    command: "redis-server --requirepass CHANGETHISPW"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    
  postgres:
    image: "postgres:16-alpine"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "CHANGETHISTOO"
      POSTGRES_DB: "dnsfookup"
      POSTGRES_USER: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
  postgres_data:
